### PR TITLE
Keycloak client -> Ansible-test

### PR DESCRIPTION
**Pull request by rrey**
##### SUMMARY

convert unittest to ansible-test integration tests

### CODE REVIEW

**Comment by elfelip** [comment]
I @rrey 
I accepted the pull request in a new branch named collection.

**Comment by rrey** [comment]
Oups again, it was meant to my fork

**Comment by elfelip** [comment]
I @rrey
You should start from inspq-devel branch. The last version of the modules are there. The inspq branch is very old and not used anymore. I probably should delete it.

**Comment by rrey** [comment]
Arrrg 😵
Ok, I´ll try a rebase 

FYI code is here : https://github.com/octo-technology/keycloak-collection

I’m migrating the integration tests first

**Pull request merged**
